name: my_discord_bot
description: A simple Discord bot.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  nyxx: ^5.0.0 # Use the latest version of nyxx
  nyxx_commands: ^5.0.0 # Use the latest version of nyxx_commands
  nyxx_interactions: ^5.0.0 # Also a good idea to include this for slash commands

dev_dependencies:
  lints: ^2.0.0
